name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Spring Boot Tests
        run: mvn test

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t zhidhasanpp/ci-demo .

      - name: Push Docker image to Docker Hub
        run: docker push zahidhasanpp/ci-demo:latest

      - name: Deploy to Production
        run: |
          # Example of deploying to a server or cloud provider
          # This step is highly specific to your deployment environment
          # For example, use SSH to copy the Docker image and run it on a server   